name: Update rules

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      # Run Python scripts to update rules
      - name: Update rules
        run: |
          python quantumult.py
          python clash.py

      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Commit & Push
        run: |
          git config --global user.email "shoujiaxin@gmail.com"
          git config --global user.name "GitHub Actions"
          git add $GITHUB_WORKSPACE/rules/
          git commit -m "build: ${{ steps.date.outputs.date }}"
          git push
